version: '3'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aftas
#      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306

  aftasbackend:
    image: aftas:latest
    container_name: aftasbackend
#    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  aftas-front:
    image: aftas-front:latest
    container_name: aftas-front
    ports:
      - 4200:4200
    depends_on:
      - aftasbackend